package com.service.model;
// Generated Mar 30, 2018 2:37:38 PM by Hibernate Tools 5.2.8.Final

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.DOMException;

import com.service.DAO.AdminDAO;
import com.service.DAO.DealerDAO;
import com.service.DAO.InventoryDAO;
import com.service.Interfaces.BillingModule;
import com.service.Interfaces.UserManagementServices;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "ITMD_515", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Admin implements java.io.Serializable,UserManagementServices,BillingModule {
	AdminDAO adminDao=new AdminDAO();

	private String aid;
	private String name;
	private Long phone;
	private String address;
	private String email;
	private String city;
	private Long zip;
	private String state;
	private String country;
	private String username;
	private String password;

	public Admin() {
	}

	public Admin(String aid, String username, String password) {
		this.aid = aid;
		this.username = username;
		this.password = password;
	}

	public Admin(String aid, String name, Long phone, String address, String email, String city, Long zip, String state,
			String country, String username, String password) {
		this.aid = aid;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.email = email;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.country = country;
		this.username = username;
		this.password = password;
	}

	@Id

	@Column(name = "AID", unique = true, nullable = false, length = 45)
	public String getAid() {
		return this.aid;
	}

	public void setAid(String aid) {
		this.aid = aid;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone")
	public Long getPhone() {
		return this.phone;
	}

	public void setPhone(Long phone) {
		this.phone = phone;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip")
	public Long getZip() {
		return this.zip;
	}

	public void setZip(Long zip) {
		this.zip = zip;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String registration(Object user) {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public void resetPassword(String newPassword,Object admin) {
		// TODO Auto-generated method stub
		System.out.println("In admin pwd reset");
		Admin ad=(Admin)admin;
		adminDao.updatePassword(newPassword,ad);
	}

	@Override
	public void forgotPassword() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void editProfile(Object editP) {
		// TODO Auto-generated method stub
		System.out.println("In admin pwd reset");
		Admin ad=(Admin)editP;
		adminDao.editProfile(editP);	
	}

	
	public String addDealer(Dealer dealer) throws DOMException, ParserConfigurationException{
		
					DealerDAO dealerd = new DealerDAO();
					return dealerd.addDealer(dealer);
					
	}
	
	public void removeDealer(Dealer dealer){
		try {
			DealerDAO dealerd = new DealerDAO();
			dealerd.removeDealer(dealer);
		} catch (DOMException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 	
	}

	@Override
	public void makeCarPayment(List<CarInventory> carscheckout, Carsale sale) {
		// TODO Auto-generated method stub
		 for(CarInventory c:carscheckout) {
				System.out.println("Admin for Car Payment update:"+c.getVid() +"<>"+ c.getPrice()+" "+c.getDsId());
		sale.setDsId(c.getDsId());
		sale.setVId(c.getVid());
		sale.setPrice(c.getPrice().toString());
		
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		 String date =sdf.format(new Date());
		Calendar cal = Calendar.getInstance();
		cal.setTime(new Date()); // Now use today date.
		cal.add(Calendar.DATE, 5); // Adding 5 days
		String output = sdf.format(cal.getTime());
		sale.setOrderDate(date);	
		sale.setStatus("0");
		sale.setDelivaryDate(output);
		System.out.println(sale.getCsid()+""+sale.getDsId()+""+sale.getVId());
		adminDao.payForCar(sale);
		InventoryDAO update = new InventoryDAO();
		update.removeCarFromInventory(c);
			}		
	}

	@Override
	public void makeCarPartPayment(List<CarPartsInventory> carpartscheckout, int valueOfCapacity,
			Carpartssale partSale) {
		// TODO Auto-generated method stub
		for(CarPartsInventory cp:carpartscheckout) {
			System.out.println("Admin in  Carparts:"+cp.getPid());
			partSale.setDsId(cp.getDsid());
			partSale.setPartId(cp.getPid());
			SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
			 String date =sdf.format(new Date());
			partSale.setDatePurchased(date);
			partSale.setStatus("0");
			partSale.setQuantity(cp.getQuantity());
			int quanttyCP=Integer.valueOf(partSale.getQuantity());
			int amt = Integer.valueOf(cp.getPrice()) * quanttyCP;
			partSale.setPrice(Integer.toString(amt));
			System.out.println(quanttyCP+ " "+"amount:"+amt);
			adminDao.payForCarPart(partSale);
			CarPartsInventory carupdate = new CarPartsInventory();
			carupdate.setPid(partSale.getPartId());
			if(quanttyCP<valueOfCapacity) {
				System.out.println("quanitty is less than capacity");
				InventoryDAO dao = new InventoryDAO();
				int updatedQuan = valueOfCapacity-quanttyCP;

				carupdate.setQuantity(Integer.toString(updatedQuan));
				dao.updateCarParts(carupdate);		}
			else if(Integer.parseInt(partSale.getQuantity())==valueOfCapacity) {
			//remove part from inventory	
				System.out.println("remove parts from inventory when quantity and capacity is equal");
				InventoryDAO dao = new InventoryDAO();
dao.removeCarPartFromInventory(carupdate);	
			}
			
		}	
	}

	public void addDealership(Dealership newDealership) {
		// TODO Auto-generated method stub
		DealerDAO dealerd = new DealerDAO();
		dealerd.addDealership(newDealership);
	}

}
