package com.service.model;
// Generated Mar 31, 2018 2:39:19 AM by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CardInformation generated by hbm2java
 */
@Entity
@Table(name="cardInformation"
    ,catalog="ITMD_515"
    , uniqueConstraints = @UniqueConstraint(columnNames="ccv") 
)
public class CardInformation  implements java.io.Serializable {


     private String creditcardnumber;
     private String nameoncard;
     private String monthExp;
     private String yearExp;
     private String ccv;

    public CardInformation() {
    }

	
    public CardInformation(String creditcardnumber) {
        this.creditcardnumber = creditcardnumber;
    }
    public CardInformation(String creditcardnumber, String nameoncard, String monthExp, String yearExp, String ccv) {
       this.creditcardnumber = creditcardnumber;
       this.nameoncard = nameoncard;
       this.monthExp = monthExp;
       this.yearExp = yearExp;
       this.ccv = ccv;
    }
   
     @Id 

    
    @Column(name="creditcardnumber", unique=true, nullable=false, length=45)
    public String getCreditcardnumber() {
        return this.creditcardnumber;
    }
    
    public void setCreditcardnumber(String creditcardnumber) {
        this.creditcardnumber = creditcardnumber;
    }

    
    @Column(name="nameoncard", length=45)
    public String getNameoncard() {
        return this.nameoncard;
    }
    
    public void setNameoncard(String nameoncard) {
        this.nameoncard = nameoncard;
    }

    
    @Column(name="month exp", length=45)
    public String getMonthExp() {
        return this.monthExp;
    }
    
    public void setMonthExp(String monthExp) {
        this.monthExp = monthExp;
    }

    
    @Column(name="year exp", length=45)
    public String getYearExp() {
        return this.yearExp;
    }
    
    public void setYearExp(String yearExp) {
        this.yearExp = yearExp;
    }

    
    @Column(name="ccv", unique=true, length=45)
    public String getCcv() {
        return this.ccv;
    }
    
    public void setCcv(String ccv) {
        this.ccv = ccv;
    }




}


