package com.service.model;
// Generated Mar 31, 2018 2:39:19 AM by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CarInventory generated by hbm2java
 */
@Entity
@Table(name="car_inventory"
    ,catalog="ITMD_515"
    , uniqueConstraints = @UniqueConstraint(columnNames="vin_number") 
)
public class CarInventory  implements java.io.Serializable {


     private String vid;
     private String dsId;
     private String vinNumber;
     private String make;
     private String model;
     private Integer year;
     private Long price;
     private String exterior;
     private Integer status;
     private String ir;
     private String interior;
     private String engine;
     private String transmission;
     private Integer citymilage;
     private Integer hwymilage;
     private Double discount;

    public CarInventory() {
    }

	
    public CarInventory(String vid, String vinNumber) {
        this.vid = vid;
        this.vinNumber = vinNumber;
    }
    public CarInventory(String vid, String dsId, String vinNumber, String make, String model, Integer year, Long price, String exterior, Integer status, String ir, String interior, String engine, String transmission, Integer citymilage, Integer hwymilage, Double discount) {
       this.vid = vid;
       this.dsId = dsId;
       this.vinNumber = vinNumber;
       this.make = make;
       this.model = model;
       this.year = year;
       this.price = price;
       this.exterior = exterior;
       this.status = status;
       this.ir = ir;
       this.interior = interior;
       this.engine = engine;
       this.transmission = transmission;
       this.citymilage = citymilage;
       this.hwymilage = hwymilage;
       this.discount = discount;
    }
   
     @Id 

    
    @Column(name="VID", unique=true, nullable=false, length=45)
    public String getVid() {
        return this.vid;
    }
    
    public void setVid(String vid) {
        this.vid = vid;
    }

    
    @Column(name="DS_ID", length=45)
    public String getDsId() {
        return this.dsId;
    }
    
    public void setDsId(String dsId) {
        this.dsId = dsId;
    }

    
    @Column(name="vin_number", unique=true, nullable=false, length=45)
    public String getVinNumber() {
        return this.vinNumber;
    }
    
    public void setVinNumber(String vinNumber) {
        this.vinNumber = vinNumber;
    }

    
    @Column(name="make", length=45)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="model", length=45)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    
    @Column(name="price")
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }

    
    @Column(name="exterior", length=45)
    public String getExterior() {
        return this.exterior;
    }
    
    public void setExterior(String exterior) {
        this.exterior = exterior;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="ir", length=45)
    public String getIr() {
        return this.ir;
    }
    
    public void setIr(String ir) {
        this.ir = ir;
    }

    
    @Column(name="interior", length=45)
    public String getInterior() {
        return this.interior;
    }
    
    public void setInterior(String interior) {
        this.interior = interior;
    }

    
    @Column(name="engine", length=45)
    public String getEngine() {
        return this.engine;
    }
    
    public void setEngine(String engine) {
        this.engine = engine;
    }

    
    @Column(name="transmission", length=45)
    public String getTransmission() {
        return this.transmission;
    }
    
    public void setTransmission(String transmission) {
        this.transmission = transmission;
    }

    
    @Column(name="citymilage")
    public Integer getCitymilage() {
        return this.citymilage;
    }
    
    public void setCitymilage(Integer citymilage) {
        this.citymilage = citymilage;
    }

    
    @Column(name="hwymilage")
    public Integer getHwymilage() {
        return this.hwymilage;
    }
    
    public void setHwymilage(Integer hwymilage) {
        this.hwymilage = hwymilage;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }




}


