package com.service.model;
// Generated Mar 31, 2018 2:39:19 AM by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carpartssale generated by hbm2java
 */
@Entity
@Table(name="carpartssale"
    ,catalog="ITMD_515"
)
public class Carpartssale  implements java.io.Serializable {


     private String psId;
     private String partId;
     private String clientId;
     private String dsId;
     private String price;
     private String quantity;
     private String datePurchased;
     private String status;

    public Carpartssale() {
    }

	
    public Carpartssale(String psId, String partId, String clientId, String dsId) {
        this.psId = psId;
        this.partId = partId;
        this.clientId = clientId;
        this.dsId = dsId;
    }
    public Carpartssale(String psId, String partId, String clientId, String dsId, String price, String quantity, String datePurchased, String status) {
       this.psId = psId;
       this.partId = partId;
       this.clientId = clientId;
       this.dsId = dsId;
       this.price = price;
       this.quantity = quantity;
       this.datePurchased = datePurchased;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="PS_ID", unique=true, nullable=false, length=45)
    public String getPsId() {
        return this.psId;
    }
    
    public void setPsId(String psId) {
        this.psId = psId;
    }

    
    @Column(name="partID", nullable=false, length=45)
    public String getPartId() {
        return this.partId;
    }
    
    public void setPartId(String partId) {
        this.partId = partId;
    }

    
    @Column(name="ClientID", nullable=false, length=45)
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="DS_ID", nullable=false, length=45)
    public String getDsId() {
        return this.dsId;
    }
    
    public void setDsId(String dsId) {
        this.dsId = dsId;
    }

    
    @Column(name="price", length=45)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="quantity", length=45)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="datePurchased", length=45)
    public String getDatePurchased() {
        return this.datePurchased;
    }
    
    public void setDatePurchased(String datePurchased) {
        this.datePurchased = datePurchased;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


