package com.service.model;
// Generated Mar 31, 2018 2:39:19 AM by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CarPartsInventory generated by hbm2java
 */
@Entity
@Table(name="car_parts_inventory"
    ,catalog="ITMD_515"
)
public class CarPartsInventory  implements java.io.Serializable {


     private String pid;
     private String dsid;
     private String name;
     private String model;
     private String make;
     private String year;
     private String quantity;
     private String price;
     private String status;
     private String type;
     private String category;
     private String ir;
     private String seller;

    public CarPartsInventory() {
    }

	
    public CarPartsInventory(String pid) {
        this.pid = pid;
    }
    public CarPartsInventory(String pid, String dsid, String name, String model, String make, String year, String quantity, String price, String status, String type, String category, String ir, String seller) {
       this.pid = pid;
       this.dsid = dsid;
       this.name = name;
       this.model = model;
       this.make = make;
       this.year = year;
       this.quantity = quantity;
       this.price = price;
       this.status = status;
       this.type = type;
       this.category = category;
       this.ir = ir;
       this.seller = seller;
    }
   
     @Id 

    
    @Column(name="PID", unique=true, nullable=false, length=45)
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }

    
    @Column(name="DSID", length=45)
    public String getDsid() {
        return this.dsid;
    }
    
    public void setDsid(String dsid) {
        this.dsid = dsid;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="model", length=45)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="make", length=45)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="year", length=45)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="quantity", length=45)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", length=45)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="category", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="ir", length=45)
    public String getIr() {
        return this.ir;
    }
    
    public void setIr(String ir) {
        this.ir = ir;
    }

    
    @Column(name="seller", length=45)
    public String getSeller() {
        return this.seller;
    }
    
    public void setSeller(String seller) {
        this.seller = seller;
    }




}


