package com.service.model;
// Generated Mar 31, 2018 2:39:19 AM by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dealership generated by hbm2java
 */
@Entity
@Table(name="dealership"
    ,catalog="ITMD_515"
)
public class Dealership  implements java.io.Serializable {


     private String dsid;
     private String did;
     private String name;
     private String phone;
     private String address;
     private String city;
     private String zip;
     private String state;
     private String country;

    public Dealership() {
    }

	
    public Dealership(String dsid) {
        this.dsid = dsid;
    }
    public Dealership(String dsid, String did, String name, String phone, String address, String city, String zip, String state, String country) {
       this.dsid = dsid;
       this.did = did;
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.city = city;
       this.zip = zip;
       this.state = state;
       this.country = country;
    }
   
     @Id 

    
    @Column(name="DSID", unique=true, nullable=false, length=45)
    public String getDsid() {
        return this.dsid;
    }
    
    public void setDsid(String dsid) {
        this.dsid = dsid;
    }

    
    @Column(name="DID", length=45)
    public String getDid() {
        return this.did;
    }
    
    public void setDid(String did) {
        this.did = did;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="zip", length=45)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="state", length=45)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


